pub mod aircraft;
pub mod autopilot;
pub mod condition;
pub mod config;
pub mod environment;
pub mod fdm;
pub mod gui;
pub mod instrumentation;
pub mod input;
pub mod multiplayer;
pub mod network;
pub mod property;
pub mod scenery;
pub mod sound;
pub mod systems;
pub mod time;
pub mod timer;

pub use aircraft::Aircraft;
pub use aircraft::config::{AircraftCatalog, AircraftConfig};
pub use aircraft::loader::load_catalog;
pub use aircraft::metadata::AircraftMetadata;
pub use autopilot::{Autopilot, AutopilotMode, AutopilotState};
pub use condition::Condition;
pub use config::AppConfig;
pub use environment::Environment;
pub use fdm::{FlightModel, FlightState};
pub use instrumentation::indicators::{AirspeedIndicator, Altimeter, AttitudeIndicator, HeadingIndicator, VerticalSpeedIndicator};
pub use instrumentation::InstrumentationState;
pub use input::InputState;
pub use multiplayer::{MultiplayerState, PlayerId};
pub use network::{Protocol, SocketAddress};
pub use property::{Property, PropertyValue};
pub use scenery::Airport;
pub use sound::{SoundEvent, SoundManager};
pub use systems::SystemsState;
pub use time::SimTime;
